// <auto-generated />
using System;
using Blog.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blog.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230411132208_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blog.Entity.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7166286-1e73-4152-8945-1d9953e5ec2d"),
                            CategoryId = new Guid("1adf36f5-41a5-46f9-9852-a871b8471de2"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nisl tincidunt eget nullam non nisi est sit. Sagittis id consectetur purus ut faucibus pulvinar elementum integer. Varius morbi enim nunc faucibus a pellentesque sit amet. Vulputate eu scelerisque felis imperdiet proin. Sed vulputate odio ut enim blandit. In massa tempor nec feugiat nisl pretium fusce id. In arcu cursus euismod quis. Sed turpis tincidunt id aliquet risus feugiat in ante metus. Et netus et malesuada fames ac turpis. Nec feugiat in fermentum posuere urna nec tincidunt praesent. Justo laoreet sit amet cursus sit amet dictum sit amet. Nunc aliquet bibendum enim facilisis gravida neque convallis. Ipsum consequat nisl vel pretium lectus quam id leo in. Imperdiet proin fermentum leo vel orci porta non pulvinar.\r\n\r\nSit amet luctus venenatis lectus magna fringilla. Odio morbi quis commodo odio aenean sed adipiscing. Congue quisque egestas diam in arcu cursus euismod quis. Porta nibh venenatis cras sed felis. Vel pretium lectus quam id leo in vitae turpis. Cum sociis natoque penatibus et magnis dis. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Pulvinar proin gravida hendrerit lectus a. Varius duis at consectetur lorem donec massa sapien faucibus et. Pretium lectus quam id leo in vitae turpis massa. Mauris sit amet massa vitae. Eget lorem dolor sed viverra ipsum. Mattis pellentesque id nibh tortor id. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sit amet luctus venenatis lectus magna fringilla urna. Nibh ipsum consequat nisl vel pretium lectus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. In fermentum et sollicitudin ac orci phasellus. Mi tempus imperdiet nulla malesuada pellentesque elit. Tellus at urna condimentum mattis pellentesque id nibh.",
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 4, 11, 16, 22, 8, 537, DateTimeKind.Local).AddTicks(2020),
                            ImageId = new Guid("25467e98-6eb6-4021-b9c8-a59fafcf8d4e"),
                            IsDeleted = false,
                            Title = "ASP.Net Core Deneme Makalesi",
                            ViewCount = 15
                        },
                        new
                        {
                            Id = new Guid("6a713dd8-393d-4033-80c6-041b5823c0ec"),
                            CategoryId = new Guid("ca10cfa7-cf30-4053-9720-9cfa4f360729"),
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Integer quis auctor elit sed vulputate mi sit. Mi quis hendrerit dolor magna eget. Sed blandit libero volutpat sed cras ornare arcu. Ut etiam sit amet nisl purus in. Egestas sed tempus urna et. Diam maecenas sed enim ut sem viverra. Id consectetur purus ut faucibus pulvinar elementum. Nunc sed id semper risus in hendrerit gravida rutrum. Neque volutpat ac tincidunt vitae semper. Amet cursus sit amet dictum sit amet justo. Suscipit adipiscing bibendum est ultricies integer. Id nibh tortor id aliquet. Amet aliquam id diam maecenas. Et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Ipsum consequat nisl vel pretium lectus. Nunc sed id semper risus in hendrerit gravida rutrum. Quam viverra orci sagittis eu volutpat odio. Libero id faucibus nisl tincidunt eget nullam non.\r\n\r\nElementum nibh tellus molestie nunc non blandit massa enim nec. In fermentum posuere urna nec tincidunt praesent. Nunc sed augue lacus viverra vitae congue eu consequat. Tempus quam pellentesque nec nam aliquam sem et. Est ultricies integer quis auctor elit sed. Lacus luctus accumsan tortor posuere ac ut consequat semper viverra. Sapien pellentesque habitant morbi tristique senectus et netus. Et magnis dis parturient montes. Enim eu turpis egestas pretium aenean. Nisl purus in mollis nunc sed id semper. Arcu non odio euismod lacinia at quis risus sed vulputate. In est ante in nibh mauris cursus.",
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 4, 11, 16, 22, 8, 537, DateTimeKind.Local).AddTicks(2033),
                            ImageId = new Guid("3eb17bea-7000-4de8-baa9-e40916f61fa9"),
                            IsDeleted = false,
                            Title = "Visual Studio Deneme Makalesi",
                            ViewCount = 15
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1adf36f5-41a5-46f9-9852-a871b8471de2"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 4, 11, 16, 22, 8, 537, DateTimeKind.Local).AddTicks(2224),
                            IsDeleted = false,
                            Name = "ASP.Net Core"
                        },
                        new
                        {
                            Id = new Guid("ca10cfa7-cf30-4053-9720-9cfa4f360729"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 4, 11, 16, 22, 8, 537, DateTimeKind.Local).AddTicks(2227),
                            IsDeleted = false,
                            Name = "Visual Studio 2022"
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("25467e98-6eb6-4021-b9c8-a59fafcf8d4e"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 4, 11, 16, 22, 8, 537, DateTimeKind.Local).AddTicks(2372),
                            FileName = "images/testimage",
                            FileType = "jpg",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("3eb17bea-7000-4de8-baa9-e40916f61fa9"),
                            CreatedBy = "Admin Test",
                            CreatedDate = new DateTime(2023, 4, 11, 16, 22, 8, 537, DateTimeKind.Local).AddTicks(2375),
                            FileName = "images/vstest",
                            FileType = "png",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Blog.Entity.Entities.Article", b =>
                {
                    b.HasOne("Blog.Entity.Entities.Category", "Category")
                        .WithMany("Articles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Entity.Entities.Image", "Image")
                        .WithMany("Articles")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Blog.Entity.Entities.Category", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Blog.Entity.Entities.Image", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
